# https://docs.travis-ci.com/user/job-lifecycle/
os: linux
dist: xenial
language: go

notifications:
  email:
    on_success: never
    on_failure: always

env:
  - LUA="lua5.1" PYTHON="python3"

addons:
  apt:
    packages:
      - luajit
      - luarocks
      - jq
      - python3
      - python3-pip

before_install:
  - sudo apt-get update

before_script:
  - luarocks install --local --lua-version=5.1 --only-server=https://luarocks.org luacheck
  - luarocks install --local --lua-version=5.1 --only-server=https://luarocks.org luafilesystem
  - luarocks install --local --lua-version=5.1 --only-server=https://luarocks.org busted
  - luarocks install --local --lua-version=5.1 --only-server=https://luarocks.org xml2lua
  - luarocks install --local --lua-version=5.1 --only-server=https://luarocks.org penlight
  - luarocks install --local --lua-version=5.1 --only-server=https://luarocks.org bitlib
  - luarocks install --local --lua-version=5.1 --only-server=https://luarocks.org luasec
  - luarocks install --local --lua-version=5.1 --only-server=https://luarocks.org lanes
  - luarocks install --local --lua-version=5.1 --only-server=https://luarocks.org copas
  - luarocks install --local --lua-version=5.1 --only-server=https://luarocks.org copas-async
  - luarocks install --local --lua-version=5.1 --only-server=https://luarocks.org luacov
  - luarocks install --local --lua-version=5.1 --only-server=https://luarocks.org cluacov
  - luarocks install --local --lua-version=5.1 --only-server=https://luarocks.org luacov-coveralls
  - pip3 install mistune==2.0.0rc1

script:
  - eval `luarocks --lua-version=5.1 path`
  - /home/travis/.luarocks/bin/luacheck . --no-color -q
  - /home/travis/.luarocks/bin/busted --lua=lua5.1 -c -o gtest .

deploy:
  provider: script
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  script: bash $TRAVIS_BUILD_DIR/.tools/deploy.sh
  on:
    branch: master

after_script:
  - /home/travis/.luarocks/bin/luacov-coveralls -v -t $COVERALLS_TOKEN